# Generated by Django 5.1.5 on 2025-01-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.CharField(max_length=100)),
                ('items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PartyLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_leader_cluster', models.CharField(max_length=100)),
                ('party_leader_name', models.CharField(max_length=200)),
                ('precinct_number', models.CharField(max_length=50)),
                ('legend', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('supporter_cluster', models.CharField(max_length=100)),
                ('supporter_name', models.CharField(max_length=200, unique=True)),
                ('supporter_barangay', models.CharField(blank=True, default='Not Provided', max_length=100, null=True)),
                ('supporter_address', models.TextField()),
                ('supporter_contact_number', models.CharField(max_length=15)),
                ('supporter_precinct_number', models.CharField(default='0000', max_length=50)),
                ('party_leader', models.CharField(blank=True, max_length=200, null=True)),
                ('party_barangay', models.CharField(blank=True, default='Not Provided', max_length=100, null=True)),
                ('party_address', models.TextField()),
                ('party_contact_number', models.CharField(max_length=15)),
                ('party_precinct_number', models.CharField(default='0000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VotersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_number', models.CharField(max_length=50)),
                ('legend', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
            ],
        ),
    ]
