# Generated by Django 5.1.5 on 2025-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterslist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
