# Generated by Django 5.1.5 on 2025-01-28 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0002_alter_voterslist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyleader',
            name='cluster_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
