# Generated by Django 5.1.5 on 2025-01-28 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0003_partyleader_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporters',
            name='party_cluster_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
