# Generated by Django 5.1.5 on 2025-01-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0004_supporters_party_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyleader',
            name='cluster_id',
        ),
    ]
