# Generated by Django 5.1.5 on 2025-01-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0006_supporters_party_legend_supporters_supporter_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='party_legend',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supporters',
            name='supporter_legend',
            field=models.TextField(max_length=20),
        ),
    ]
