# Generated by Django 5.1.4 on 2025-01-29 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0008_supporters_supporter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporters',
            name='supporter_type',
        ),
        migrations.AddField(
            model_name='partyleader',
            name='party_chairman',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supporters',
            name='party_chairman',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
