# Generated by Django 5.1.4 on 2025-01-29 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_encoding', '0009_remove_supporters_supporter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporters',
            name='supporter_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
